name: biodart
publish_to: none
workspace:
  - genomics/
  - fasta/
  - benchmark/

environment:
  sdk: ">=3.7.0-209.1.beta <4.0.0"

dependencies:
  collection:
  meta:

dev_dependencies:
  lint:
  test:

# For ease of development.
dependency_overrides:
  readers:
    path: ../readers
