name: biodart
workspace:
  - hic/
  - genomics/
  - fasta/

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  collection:
  meta:

dev_dependencies:
  lint:
  test:

# For ease of development.
dependency_overrides:
  readers:
    path: ../readers
