name: genomics
description: Implementation of common genomics algorithms and data structures.
version: 0.0.1-beta
publish_to: "none"

resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  collection:
  meta:
