name: fasta
description: A library providing support for the FASTA and FASTQ.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.7.0-209.1.beta <4.0.0"

resolution: workspace

dependencies:
  collection:
  meta:
  readers:

dev_dependencies:
  test:
