name: hic
description: A single-file library to read Hi-C data.
version: 0.0.2-wip
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  collection:
  genomics:
  meta:
  readers:
