name: hic
description: A single-file library to read Hi-C data.
version: 0.0.1-wip
publish_to: none

resolution: workspace

environment:
  sdk: 3.6.0-216.1.beta

dependencies:
  collection:
  genomics:
  meta:
  readers:
    git:
      url: https://github.com/FabrizioG202/readers.git

dev_dependencies:
  test:
